version: "2.4"
services:
  init:
    image: alpine:latest
    command:
      - echo
      - "Hello world!"
  db:
    image: localpg
    build:
      context: .
      dockerfile: Postgres.Dockerfile
    healthcheck:
      test: pg_isready -U postgres
      interval: 2s
      timeout: 2s
      retries: 10
      start_period: 1s
    environment:
      POSTGRES_PASSWORD: supersecret
    tmpfs:
      - /var/lib/postgresql/data
    depends_on:
      init:
        condition: service_completed_successfully
  web:
    image: alpine:latest
    command:
      - echo
      - "Hello foobar (after hello world)!"
    depends_on:
      db:
        condition: service_healthy
